name: Docs

on:
  pull_request:
  push:
    tags:
    - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    # must come after checkout
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - run: sudo apt-get install pandoc
    # - run: conda install -c conda-forge root
    - run: pip install .[doc]
    - run: make doc
    - uses: actions/upload-pages-artifact@v3
      with:
        path: 'build/html'

  deploy:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.ref, '/tags/')
    needs: build
    # Set permissions to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/configure-pages@v4
    - uses: actions/deploy-pages@v4
