name: Release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PIP_ONLY_BINARY: ":all:"

jobs:
  release:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/sweights
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0  # needed by setuptools_scm
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - run: python -m pip install --upgrade pip build
    - run: python -m build
    - run: python -m pip install --prefer-binary $(echo dist/*.whl)'[test]'
    - run: python -m pytest

    - uses: pypa/gh-action-pypi-publish@release/v1
      if: github.event_name == 'push' && contains(github.event.ref, '/tags/')
